[versions]
minSdk = "21"
compileSdk = "34"
targetSdk = "34"

androidgradleplugin = "8.5.2"
kotlin = "2.0.0"
kotlinxcoroutines = "1.8.1"
ktlint = "1.3.1"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.9.2" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version = "1.3.7" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version = "1.8.4" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.2.1" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxcoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxcoroutines" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.14" }
material = { module = "com.google.android.material:material", version = "1.12.0" }
mock = { module = "io.mockk:mockk", version = "1.13.12" }
plugin-android-cache-fix = { module = "org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin", version = "3.0.1" }
plugin-androidgradleplugin = { module = "com.android.tools.build:gradle", version.ref = "androidgradleplugin" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.9.20" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version = "1.11.0" }
plugin-paparazzi = { module = "app.cash.paparazzi:paparazzi-gradle-plugin", version = "1.3.3" }
plugin-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.33.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.12.1" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

[plugins]
codequalitytools = { id = "com.vanniktech.code.quality.tools", version = "0.24.0" }
dependencygraphgenerator = { id = "com.vanniktech.dependency.graph.generator", version = "0.8.0" }
